spring:
  application:
    name: dolphin
  datasource:
    url: jdbc:postgresql://localhost:5432/dolphin
    username: springuser
    password: springpassword

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.flywaydb: DEBUG

dolphin:
  security:
    jwt:
      secret: ${JWT_SECRET:n8UDq4vd3br1c0JB5frADb5auzu1/WqXpMGQge94OVE=}
      expiration-ms: 900000

